all:baker salesman customer
baker:baker.c
	gcc baker.c -o baker -lpthread
salesman:salesman.c
	gcc salesman.c -o salesman -lpthread
customer:customer.c
	gcc customer.c -o customer
clean:
	rm baker salesman customer